name: Pull Request Check

on: 
  pull_request:
    branches: [ main ]

permissions: write-all

jobs:
  generation:
    name: Content Generator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          ref: ${{github.head_ref}}

      - name: Setup Node.js
        uses: actions/setup-node@v3

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        run: |
         echo hello
         exit 0
