name: Examples Type Chacker

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: Type Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Running Clean Up Code
        run: |
            npm run check